# Realizes: docs/CLIENT-TEMPLATE-ARCHITECTURE.md · the thin-client contract
@cms-admin @e2e
Feature: The CMS admin entry is served and wired
  As a site editor
  I want the /admin content editor to load and be configured
  so that an assembled thin client ships a working editor entry point

  # SHALLOW on purpose: booting Sveltia or signing in needs the platform worker
  # (git-proxy + our auth popup), which isn't available against a local preview.
  # This only proves the admin page is served and wired — the CMS bundle is
  # referenced and the per-build config.yml was generated by ferst-cms-config.
  Scenario: The admin page is served and references the CMS bundle
    When the visitor opens the CMS admin page
    Then the admin page is served successfully
    And the admin page is titled "Content editor"
    And the admin page references the CMS bundle
    And the generated CMS config is served
